### ISSUE TITLE
update Entware mipsel

### ISSUE THREAD

**Issue by MVoz** [nongiach/arm_now#22]
Entware-ng and Entware-3x = Entware
https://github.com/Entware/Entware

```
arm_now resize 2G
arm_now start mips32el
```

install 
`wget -O - http://bin.entware.net/mipselsf-k3.4/installer/generic.sh | /bin/sh`
and ...
bug fix
`busybox --install -s /bin`
or

```
rm -f /opt/bin/wget
ln -s /bin/busybox /opt/bin/wget
```

```
opkg install gcc
Installing gcc (6.3.0-1b) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/gcc_6.3.0-1b_mipsel-3.4.ipk
```

https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation

`wget -qO- http://bin.entware.net/mipselsf-k3.4/include/include.tar.gz | tar xvz -C /opt/include`

install local
http://bin.entware.net/mipselsf-k3.4

```
wget http://bin.entware.net/mipselsf-k3.4/gcc_6.3.0-1b_mipsel-3.4.ipk
opkg install http://.../name.ipk
```

**Comment by nongiach** [comment]
sorry for the delay, you are amazing.
I'll have to merge this thx for giving me work haha, damn it

**Comment by nongiach** [comment]
I did you steps you showed and this is what happened for me.

```
# gcc
/opt/lib/gcc/mipsel-openwrt-linux-gnu/6.3.0/crt1.o: In function `__start':
(.text+0xc): undefined reference to `main'
/opt/lib/gcc/mipsel-openwrt-linux-gnu/6.3.0/crt1.o: In function `__start':
(.text+0x10): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
Did you had the same?

**Comment by MVoz** [comment]
https://github.com/Entware/Entware/issues
