### ISSUE TITLE
Add python dependencies to README

### ISSUE THREAD

**Issue by E3V3A** [nongiach/arm_now#27]
Please add info on what dependencies are required both by pip packages and python versions etc. 
What about OS?

**Comment by nongiach** [comment]
yo,
like all python project there is the requirements.txt that you can pip3 install -r requirements.txt.
Regarding the other dependencies, the project detects them automatically and give you the adapted instructions for your system.
I would love to make it more clear for all users, so I will add your requested information.

Thank you for the feedback.
