### ISSUE TITLE
Can't start with ubuntu's latest QEMU

### ISSUE THREAD

**Issue by 0xKira** [nongiach/arm_now#37]
I'm on the latest ubuntu 18.04.3 with the QEMU installed from apt. When I start arm_now, the error message is shown below:
```
qemu-system-arm: -nic: invalid option
```
My QEMU version:
```
(arm_now) ~/tmp ᐅ qemu-system-arm -version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.15)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```
But the `-nic` option is introduced in QEMU 2.12. See the post here: https://www.qemu.org/2018/05/31/nic-parameter/

**Comment by MorphBC** [comment]
Try this:

https://askubuntu.com/questions/1067722/how-do-i-install-qemu-3-0-on-ubuntu-18-04

**Comment by jlblancoc** [comment]
:+1: to the proposal of @MorphBC , it works perfectly. At least, tested with qemu 3.1.1.1 sources.

This issue could be closed with that solution, IMO.

**Comment by SakiiR** [comment]
Is that fine to everybody if we close at this point ? :)

**Comment by ejdoh1** [comment]
I just changed a line to following and seems to start ok:
$ cat ./.local/lib/python3.6/site-packages/arm_now/arm_now.py | grep nic
    args = ["-net nic -net user"]

**Comment by nongiach** [comment]
Hello,

I just tested with docker on the latest version of Ubuntu, It was just fine.

I'm closing this issue, feel free to reopen.

Have a good day.
