### ISSUE TITLE
Compiling Go package on MIPS32EL for openwrt

### ISSUE THREAD

**Issue by sxiii** [nongiach/arm_now#38]
Hi! I've got a question and hope someone from the community can help me.

Question is quite general. I need to compile google cloud-print-conntector; which is written in Go language; for the Lantiq XRX200 CPU; which is probably what MIPS32EL is also. This all stuff have to work in the future on the Lantiq device with OpenWRT firmware (so I will have also to create a package for it). In general, do you think, is it possible to do that?

Thanks for help!

**Comment by nongiach** [comment]
Hi sxii,

arm_now can't help you out of the box for the compilation process
But arm_now helps you to run the binary on a qemu emulated mips32el.

```sh
$ ls
your_binary
$ arm_now start mips32el --sync
# ./your_binary
```

Visit the wiki for more information about the compilation process, altough this will differ from Go compilation.
https://github.com/nongiach/arm_now/wiki/5.3-Compile-and-play-2048-on-ARM,-MIPS-and-PowerPc64-within-a-minute

Thanks.
