### ISSUE TITLE
always url error , i think the network is ok 

### ISSUE THREAD

**Issue by frustreated** [nongiach/arm_now#42]
File "/usr/lib/python3.5/urllib/request.py", line 1263, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

**Comment by nongiach** [comment]
Hello,

we cannot reproduce your error!
Can you please provide the exact step that you went trough with arm_now and also describe your system configuration?

Thanks

**Comment by nongiach** [comment]
Hello,

you closed the issue, I guess you found the solution!
Can you please describe the issue and the solution?

Well done!
